# docker-compose.yml
version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./volume_static:/staticfiles
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: gunicorn --bind 0.0.0.0:8000 envirmate.wsgi:application
    volumes:
      - ./volume_static:/usr/src/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: envirmate_db
      MYSQL_USER: envirmate
      MYSQL_PASSWORD: envirmate
      MYSQL_ROOT_PASSWORD: envirmate
    volumes:
      - ../db/data:/var/lib/mysql
      - ../db/data/conf.d:/etc/mysql/conf.d
