# docker-compose.yml
version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80/tcp"
    volumes:
      - ../envirmate/nginx:/etc/nginx/conf.d
      - ../envirmate/volume_static:/staticfiles
      - ../envirmate/volume_media:/media
    depends_on:
      - web
  web:
    image: pcj0198/envirmate:latest
    container_name: web
    command: gunicorn --bind 0.0.0.0:8000 envirmate.wsgi:application
    volumes:
      - ../envirmate/volume_static:/usr/src/app/staticfiles
      - ../envirmate/volume_media:/usr/src/app/media
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: envirmate_db
      MYSQL_USER: envirmate
      MYSQL_PASSWORD: ckswhd123~
      MYSQL_ROOT_PASSWORD: ckswhd123~
    volumes:
      - ../envirmate/db/data:/var/lib/mysql
      - ../envirmate/db/data/conf.d:/etc/mysql/conf.d
